cod_bdi <- tibble::tribble(
  ~cod_bdi,                                                  ~desc,
      "02",                                          "LOTE PADRAO",
      "05",            "SANCIONADAS PELOS REGULAMENTOS BMFBOVESPA",
      "06",                                       "CONCORDATARIAS",
      "07",                            "RECUPERACAO EXTRAJUDICIAL",
      "08",                                 "RECUPERAÇÃO JUDICIAL",
      "09",   "RAET - REGIME DE ADMINISTRACAO ESPECIAL TEMPORARIA",
      "10",                                   "DIREITOS E RECIBOS",
      "11",                                          "INTERVENCAO",
      "12",                                  "FUNDOS IMOBILIARIOS",
      "14",                          "CERT.INVEST/TIT.DIV.PUBLICA",
      "18",                                           "OBRIGACÕES",
      "22",                                     "BÔNUS (PRIVADOS)",
      "26",                      "APOLICES/BÔNUS/TITULOS PUBLICOS",
      "32",             "EXERCICIO DE OPCOES DE COMPRA DE INDICES",
      "33",              "EXERCICIO DE OPCOES DE VENDA DE INDICES",
      "38",                        "EXERCICIO DE OPCOES DE COMPRA",
      "42",                         "EXERCICIO DE OPCOES DE VENDA",
      "46",                                "LEILAO DE NAO COTADOS",
      "48",                               "LEILAO DE PRIVATIZACAO",
      "49", "LEILAO DO FUNDO RECUPERACAO ECONOMICA ESPIRITO SANTO",
      "50",                                               "LEILAO",
      "51",                                         "LEILAO FINOR",
      "52",                                         "LEILAO FINAM",
      "53",                                         "LEILAO FISET",
      "54",                              "LEILAO DE ACÕES EM MORA",
      "56",                           "VENDAS POR ALVARA JUDICIAL",
      "58",                                               "OUTROS",
      "60",                                    "PERMUTA POR ACÕES",
      "61",                                                 "META",
      "62",                                      "MERCADO A TERMO",
      "66",         "DEBENTURES COM DATA DE VENCIMENTO ATE 3 ANOS",
      "68",   "DEBENTURES COM DATA DE VENCIMENTO MAIOR QUE 3 ANOS",
      "70",                        "FUTURO COM RETENCAO DE GANHOS",
      "71",                                    "MERCADO DE FUTURO",
      "74",                          "OPCOES DE COMPRA DE INDICES",
      "75",                           "OPCOES DE VENDA DE INDICES",
      "78",                                     "OPCOES DE COMPRA",
      "82",                                      "OPCOES DE VENDA",
      "83",                                           "BOVESPAFIX",
      "84",                                             "SOMA FIX",
      "90",                               "TERMO VISTA REGISTRADO",
      "96",                                  "MERCADO FRACIONARIO",
      "99",                                          "TOTAL GERAL"
  )

cod_mercado <- tibble::tribble(
  ~mercado, ~desc,
     "010", "VISTA",
     "012", "EXERCÍCIO DE OPÇÕES DE COMPRA",
     "013", "EXERCÍCIO DE OPÇÕES DE VENDA",
     "017", "LEILÃO",
     "020", "FRACIONÁRIO",
     "030", "TERMO",
     "050", "FUTURO COM RETENÇÃO DE GANHO",
     "060", "FUTURO COM MOVIMENTAÇÃO CONTÍNUA",
     "070", "OPÇÕES DE COMPRA",
     "080", "OPÇÕES DE VENDA"
)

